// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using miniEShop.Infrastructure.Data;

#nullable disable

namespace miniEShop.Infrastructure.Migrations
{
    [DbContext(typeof(MiniEShopDbContext))]
    partial class MiniEShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("miniEShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kırtasiye"
                        });
                });

            modelBuilder.Entity("miniEShop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "13 inç ekranlı ultrabook",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Laptop Dell XPS 13",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "RGB gaming mouse",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Gaming Mouse Logitech",
                            Price = 850m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Cherry MX anahtarlı klavye",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Mechanical Keyboard",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "4K çözünürlüklü monitör",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Monitor 27 inch 4K",
                            Price = 8500m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "NVMe M.2 SSD",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "SSD Samsung 1TB",
                            Price = 3200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Full HD webcam",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Webcam Logitech C920",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "7 portlu USB hub",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "USB Hub 7 Port",
                            Price = 450m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Ayarlanabilir laptop standı",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Laptop Stand",
                            Price = 320m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Pamuklu beyaz t-shirt",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "T-Shirt Beyaz",
                            Price = 180m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Slim fit jean pantolon",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Jean Pantolon",
                            Price = 450m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Unisex kapüşonlu sweatshirt",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Kapüşonlu Sweatshirt",
                            Price = 320m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Koşu ayakkabısı",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Spor Ayakkabı",
                            Price = 850m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Suni deri ceket",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Ceket Deri",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Çiçek desenli elbise",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Elbise Yazlık",
                            Price = 280m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Ayarlanabilir şapka",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Şapka Baseball",
                            Price = 120m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Pamuklu spor çorap seti",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Çorap Spor 3'lü",
                            Price = 85m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Renkli kalem seti",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Kalem Seti 12'li",
                            Price = 45m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "100 sayfa kareli defter",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Defter A4 Kareli",
                            Price = 25m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Beyaz silgi",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Silgi Beyaz",
                            Price = 8m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Plastik cetvel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Cetvel 30cm",
                            Price = 12m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Metal kalemtıraş",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Kalemtıraş Metal",
                            Price = 15m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "21g yapıştırıcı stick",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Yapıştırıcı Stick",
                            Price = 18m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "A4 plastik dosya",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Dosya Plastik",
                            Price = 35m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Renkli yapışkanlı notlar",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg",
                            Name = "Post-it Notlar",
                            Price = 22m
                        });
                });

            modelBuilder.Entity("miniEShop.Entities.Product", b =>
                {
                    b.HasOne("miniEShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("miniEShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
